name: Scheduled run

on:
  #schedule:
  #  - cron: "0 */3 * * *"  # every 3 hours
  workflow_dispatch: {}

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run OLX bot (single check)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OLX_TITLE_KEYWORDS: ${{ vars.OLX_TITLE_KEYWORDS }}
        run: |
          python olx_bot.py

